#!/usr/bin/env bash
# configure a brand new NGINX server

sudo apt-get -y update
sudo apt-get -y install nginx

sudo sh -c 'echo "Hello World!" > /var/www/html/index.html'

echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

sudo sed -i "/listen 80 default_server;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default

sudo sed -i "/listen 80 default_server;/a error_page 404 /404.html;" /etc/nginx/sites-available/default

sudo sed -i '14a \\tadd_header X-Served-By '"${HOSTNAME}"';' /etc/nginx/nginx.conf

sudo ufw allow 'Nginx HTTP'

sudo service nginx restart
