#!/usr/bin/env bash
# configure a load-balancing server

sudo apt-get install -y software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-1.8
sudo apt-get update -y
sudo apt-get install -y haproxy

sudo chown ubuntu /etc/haproxy/haproxy.cfg

sudo echo \
     "
frontend localnodes
     bind *:80
     mode http
     default_backend nodes

backend nodes
     mode http
     balance roundrobin
     server 139552-web-01 18.208.119.87
     server 139552-web-02 34.227.94.41" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
