#!/usr/bin/env bash
# change nginx server to listen on port 80 and restart

sudo sed -i "\
listen 80 default_server;
listen [::]:80 default_server" /etc/nginx/sites-enabled/default
sudo service nginx restart
