#!/usr/bin/env bash
#make your fix short and sweet.
rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
pkill -f --signal 1 "/usr/sbin/nginx"
