#!/usr/bin/env bash
# change nginx server to listen on port 80 and restart
sudo rm /etc/nginx/sites-enabled/default
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
pkill -f --signal 1 "/usr/sbin/nginx"
