#!/usr/bin/env bash
# the script loops form 1 - 10 and:
# display bad luck for the forth loop iteration
# displays good luck for the 8th loop iteration
# displays Best School for the other Iterations

cnt=1
while [ $cnt -le 10 ]
do
    if [ $cnt -eq 4 ]
    then
	echo "bad luck"
    elif [ $cnt -eq 8 ]
    then
	echo "good luck"
    else
	echo "Best School"
    fi
    ((cnt += 1))
done
