#!/usr/bin/env bash
#script that displays the content of the current directory
#is a list format
#where only the part of the name after the first dash is displayed

for i in *
do
    echo "$i" | cut -f 2- -d '-'
done
