#!/usr/bin/env bash
# nginx running as user nginx on 8080
chmod 777 /etc/nginx/nginx.conf
pkill apache2
# sed global replace 80 with 8080
sed -i 's,80,8080,g' /etc/nginx/sites-enabled/default
sudo -u nginx service nginx start
