#!/usr/bin/env bash
# a script that creates an RSA key pair. bits in the created key
# to be created 4096 Name of the created private key must be school
# passphrase betty

ssh-keygen -t rsa -b 4096 -f school -N betty